# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Hurray
tagline:          'Hyde theme evale'
description:      'Peanut butter'
url:              https://doubleplusc.github.io/hyde.github.io/
baseurl:          /

author:
  name:           'doubleplusc'
  url:            https://doubleplusc.github.com

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
